username: "technical_test Workflow"

pretext: Workflow started via trigger *{{eventName}}*

fields:
  - title: Initial Parameters
    value: |-
      Environment: *inputs.Environment*
      Replicas: *inputs.Replicas*
    short: true
  - title: Started by {{actor}}
    value: |-
      {{ref}} ({{refType}})
    short: true

footer: >-
  Job Status: *{{jobStatus}}* | <{{repositoryUrl}}|{{repositoryName}}> | {{workflow}} #{{runNumber}}

colors:
  success: '#5DADE2'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'