username: "technical_test Workflow"

fields:
  - title: Results
    value: |-
      GCR File Name: inputs.FILENAME
      GKS NAMESPACE: inputs.GKS_NAMESPACE
      APP NAME: inputs.APP_NAME
      URL: <http://inputs.URL|inputs.URL>
      Ingress IP address: inputs.IngressIP
      Build Finished: <{{workflowRunUrl}}|{{jobStatus}}>
    short: false

colors:
  success: '#5DADE2'
  failure: '#884EA0'
  cancelled: '#A569BD'
  default: '#7D3C98'

icons:
  success: ':white_check_mark:'
  failure: ':grimacing:'
  cancelled: ':x:'
  skipped: ':heavy_minus_sign:'
  default: ':interrobang:'
