# Create NS
apiVersion: v1
kind: Namespace
metadata:
  name:  prod

---

# Create service
apiVersion: v1
kind: Service
metadata:
  name: taskurban-srv
  namespace: prod
spec:
  selector:
    app: taskurban
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000

---

# Deploy apps
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskurban-deploy
  namespace: prod
spec:
  selector:
    matchLabels:
      app: taskurban
  replicas: 1
  template:
    metadata:
      labels:
        app: taskurban
    spec:
      containers:
      - name: taskurban
        image: gcr.io/taskurban/technical_test:master-de42fa2
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000

---

# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taskurban-srv
            port:
              number: 80

