# Sending Metrics to Prometheus

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: prometheus-templatename-srv # Uniq Service Name
  # namespace: metrics
spec:
  endpoints:
    - honorLabels: true
      path: /metrics
      port: http                    # PortName
      scheme: http
      scrapeTimeout: 10s            # default = 30s
  jobLabel: prometheus
  namespaceSelector:
    matchNames:
      - templatename-srv            # change to Environment
  selector:
    matchLabels:
      metrics: templatename-env     # environment-label
