name: Build and Deploy to GKE

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  APP_NAME: "technical-test"
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  slackStart: "GHActions/slack_start.yml"
  slackError: "GHActions/slack_error.yml"
  slackFinish: "GHActions/slack_build.yml"
  replicas_check: ( 1 2 3 4 5 )

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment: (test|dev|prod)"
        type: choice
        default: "prod"
        options:
        - test
        - dev
        - prod
        required: true
      replicas:
        description: "Replicas: (1-5)"
        default: "3"
        required: true

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: Checkout
      uses: actions/checkout@v3

    # Check input variables
    - name: Check input Variables
      id: Check_input_Variables
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "github.ref_name = ${{ github.ref_name }}"
        echo "github.ref_type = ${{ github.ref_type }}"
        echo "helm version = $(helm version)"
          # Check and Print input data
        echo ""
          # Output Environment
        echo "--- Environment: <${{ github.event.inputs.env }}> ---"
          # Check replicas
        if [[ " ${replicas_check[@]} " =~ " ${{ github.event.inputs.replicas }} " ]]; then 
          echo "--- Number of replicas: <${{ github.event.inputs.replicas }}> are correct ---"
        else 
          echo "ERROR ===> Number of replicas: <${{ github.event.inputs.replicas }}> are incorrect."
          echo "Availible Number of replicas: ${replicas_check[@]}"
          sed -i "s/inputs.ErrorReason/Number of replicas: *${{ github.event.inputs.replicas }}* are incorrect/" $slackError
          cp $slackError slackstart.yml
          exit 1
        fi

    # Slack Start Notification
    - name: Slack Notification Start
      id: Slack_Notification_Start
      run: |
        sed -i 's/inputs.Environment/${{ github.event.inputs.env }}/' $slackStart
        sed -i 's/inputs.Replicas/${{ github.event.inputs.replicas }}/' $slackStart 
        # sed -i "/inputs./,+1 d" $slackStart  # delete all strings with "inputs."
        cp $slackStart slackstart.yml
        cat slackstart.yml
    - uses: act10ns/slack@v1.5.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: "#test-chat-ops"
        config: slackstart.yml
      if: always()

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      id: Setup_gcloud
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    - run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0
      id: get_gke_credentials
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Setting Environment Variables
    - name: Setting Environment Variables
      id: Setting_Environment_Variables
      run: |-
        # HASH short commit
          branch_name=`git symbolic-ref HEAD 2>/dev/null | cut -d"/" -f 3`  # GETTING CURRENT BRANCH NAME
          commit_hash=`git rev-parse --short HEAD`  # CURRENT COMMIT short HASH
          PROJECT_VERSION=${branch_name}-${commit_hash}
          echo "PROJECT_VERSION = $PROJECT_VERSION"
          echo "::set-output name=PROJECT_VERSION::$PROJECT_VERSION"
        # FILENAME
          FILENAME="gcr.io/$PROJECT_ID/$APP_NAME:$PROJECT_VERSION"
          echo "::set-output name=FILENAME::$FILENAME"
        # URL (Add to your /etc/hosts string: `IngressAdrress *.taskurban.com`)
          if [[ ${{ github.event.inputs.env }} == "prod" ]] ; then
            URL="taskurban.com"
          else
            URL="${{ github.event.inputs.env }}.taskurban.com"
          fi
          echo "::set-output name=URL::$URL"

    # Build the Docker image
    - name: Build
      id: Build
      run: |-
        FILENAME="${{  steps.Setting_Environment_Variables.outputs.FILENAME  }}"
        docker build \
          --tag $FILENAME \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          application/.

    # Push the Docker image to Google Container Registry
    - name: Publish
      id: Publish
      run: |-        
        FILENAME="${{  steps.Setting_Environment_Variables.outputs.FILENAME  }}"
        docker push $FILENAME

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      id: Deploy_app
      run: |-
        FILENAME="${{  steps.Setting_Environment_Variables.outputs.FILENAME  }}"
        # Change APPnamespace in Service and Prometheus Metrics yml-files
          sed -i "s|APPnamespace|${{ github.event.inputs.env }}|g" deploy-app/*.yml
        # Add App-Name
          sed -i "s|templatename|$APP_NAME|g" deploy-app/*.yml
        # Change Docker-image and Replicas
          sed -i "s|docker_image|$FILENAME|g" deploy-app/deploy.yml
          sed -i "s|replicas: 3|replicas: ${{ github.event.inputs.replicas }}|g" deploy-app/deploy.yml
        # change URL taskurban.com
          sed -i "s|taskurban.com|${{  steps.Setting_Environment_Variables.outputs.URL  }}|g" deploy-app/ingress.yml
        # Deploy in NameSpace = $inputs.env
          kubectl apply -n ${{ github.event.inputs.env }} -f deploy-app/deploy.yml
          kubectl apply -n ${{ github.event.inputs.env }} -f deploy-app/service.yml
          kubectl apply -n ${{ github.event.inputs.env }} -f deploy-app/ingress.yml
        # Deploy Prometheus metrics Pod
          kubectl apply -n ${{ github.event.inputs.env }} -f deploy-app/promMetrics.yml
        # Get Ingress IP-adress
          ingress_ip=$(kubectl get ingress -n ${{ github.event.inputs.env }} | sed -n 2p | awk -F " " '{print $4}')
          echo "::set-output name=INGRESSIP::$ingress_ip"

    # Slack Finish Notification
    - name: Slack Finish Notification
      id: Slack_Notification_Finish
      run: |
        sed -i "s|inputs.FILENAME|*${{ steps.Setting_Environment_Variables.outputs.FILENAME }}*|" $slackFinish
        sed -i "s|inputs.APP_NAME|*$APP_NAME*|" $slackFinish
        sed -i "s|inputs.GKS_NAMESPACE|*${{ github.event.inputs.env }}*|" $slackFinish
        sed -i "s|inputs.IngressIP|*${{ steps.Deploy_app.outputs.INGRESSIP }}*|g" $slackFinish
        sed -i "s|inputs.URL|${{ steps.Setting_Environment_Variables.outputs.URL }}|g" $slackFinish
        cp $slackFinish slack.yml
        cat slack.yml
    - uses: act10ns/slack@v1.5.0
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: "#test-chat-ops"
        config: slack.yml
      if: always()
